spring:

  #session
  session:
    store-type: redis
    timeout: 2592000
    #redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
    # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/no-ai-code
    username: root
    password: 1234
  profiles:
    active: local
  application:
    name: ai-no-code-backhend
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: org.example.ainocode.controller
# knife4j1
knife4j:
  enable: true
  setting:
    language: zh_cn
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    region: ap-shanghai
    bucket: hsl-work-1393672660
